[package]
name = "installer"
version = "0.1.0"
edition = "2021"

[dependencies]
config = "0.13.3"
env_logger = "0.10.0"
log = "0.4.17"
rpassword = "7.2.0"
noshell = { git = "https://github.com/eddieKaa/noshell.git", rev = "46c6c29" }

[profile.release]
strip = true
lto = true
panic = "abort"
